openshift/backplane-cli

- OWNERS
This PR serves the purpose of adding OWNERS to bp-cli.
> Adding OWNERS file to bp-cli

- pkg/utils/cluster_test.go
> Clean up naming conventions

- cmd/ocm-backplane/root.go
- cmd/ocm-backplane/script/describeScript.go
- cmd/ocm-backplane/script/describeScript_test.go
- cmd/ocm-backplane/script/listScripts.go
- cmd/ocm-backplane/script/listScripts_test.go
- cmd/ocm-backplane/script/script.go
- cmd/ocm-backplane/script/script_suite_test.go
feature
This PR serves the purpose of migrating scripts command to this repository
[OSD-14688](https://issues.redhat.com//browse/OSD-14688)
_Resolves #_
[OSD-14688](https://issues.redhat.com//browse/OSD-14688)
- [yes ] Ran unit tests locally
- [yes] Validated the changes in a cluster
> OSD-14688:Migrating Managed scripts

- cmd/ocm-backplane/root.go
- cmd/ocm-backplane/status/status.go
Feature
This PR serves the purpose of migrating status command for bp-cli
[OSD-14686](https://issues.redhat.com/browse/OSD-14686)
_Resolves #_
[OSD-14686](https://issues.redhat.com/browse/OSD-14686)
- [Yes ] Ran unit tests locally
- [Yes ] Validated the changes in a cluster
> OSD-14686: Migrating status command

- cmd/ocm-backplane/root.go
- cmd/ocm-backplane/version/version.go
- pkg/info/info.go
feature
Migrating backplane-cli version 
[OSD-14690](https://issues.redhat.com//browse/OSD-14690)
- [ Yes ] Ran unit tests locally
- [ Yes ] Validated the changes in a cluster
- [ No ] Included documentation changes with PR
> Migrate backplane-cli: version

- Makefile
- cmd/ocm-backplane/root.go
- cmd/ocm-backplane/testJob/createTestJob.go
- cmd/ocm-backplane/testJob/createTestJob_test.go
- cmd/ocm-backplane/testJob/getTestJob.go
- cmd/ocm-backplane/testJob/getTestJobLogs.go
- cmd/ocm-backplane/testJob/getTestJob_test.go
- cmd/ocm-backplane/testJob/testJob.go
- cmd/ocm-backplane/testJob/testJob_suite_test.go
feature
Adding test job create and get commands 
_Resolves #_ [OSD-14689](https://issues.redhat.com/browse/OSD-14689)
> OSD-14689: Add backplane-cli create and get testjob commands

- Makefile
- cmd/ocm-backplane/login/login.go
- cmd/ocm-backplane/login/login_suite_test.go
- cmd/ocm-backplane/login/login_test.go
- cmd/ocm-backplane/logout/logout.go
- cmd/ocm-backplane/logout/logout_test.go
- cmd/ocm-backplane/root.go
- go.mod
- pkg/utils/util.go
What type of PR is this?
feature
What this PR does / Why we need it?
This PR is for migrating backplane login/logout
Which Jira/Github issue(s) does this PR fix?
[OSD-14683](https://issues.redhat.com/browse/OSD-14683)
Pre-checks (if applicable)
* [ Yes] Ran unit tests locally
* [ Yes] Validated the changes in a cluster
* [No] Included documentation changes with PR
> Migrating backplane-cli login & logout

- Makefile
- cmd/ocm-backplane/managedJob/createManagedJob.go
- cmd/ocm-backplane/managedJob/createManagedJob_test.go
- cmd/ocm-backplane/managedJob/deleteManagedJob.go
- cmd/ocm-backplane/managedJob/deleteManagedJob_test.go
- cmd/ocm-backplane/managedJob/getManagedJob.go
- cmd/ocm-backplane/managedJob/getManagedJob_test.go
- cmd/ocm-backplane/managedJob/logsManagedJob.go
- cmd/ocm-backplane/managedJob/managedJob.go
- cmd/ocm-backplane/managedJob/managedJob_suite_test.go
- cmd/ocm-backplane/root.go
feature
This PR includes managed jobs create, delete. list and getting logs commands
_Resolves #_ [OSD-14687](https://issues.redhat.com/browse/OSD-14687)
You have to log in to the cluster before executing managed jobs commands
> OSD-14687: Add Backplane CLI managed jobs add,get,delete,log commands

- README.md
- docs/PS1-setup.md
- docs/design.md
_(documentation)_
This pull request adapts the documentation from the internal backplane repository for a public audience. It adds the old README and the guide for setting up the bash/zsh PS1. 
_Resolves #_ [OSD-15318](https://issues.redhat.com/browse/OSD-15318)
> Migrate docs 

- .codecov.yml
- Makefile
- hack/codecov.sh
Feature
Onboards backplane-cli into codecov.io for coverage tests
_Resolves #_
https://issues.redhat.com/browse/OSD-15356
> OSD-15356: Onboard codecov.io

- Makefile
- hack/codecov.sh
Cleanup
Modifies the test target to a better extent
> Modify test target

- Makefile
- cmd/ocm-backplane/testJob/createTestJob_test.go
Bug
The PR intends to fix the intermittent coverage checks failing
> Fix coverage fails

- pkg/utils/util.go
> fix panic when the error returned is not the backplane error struct

- README.md
feature
* This will show codecov coverage percentage in the readme
> Add codecov, go reference and license badges

- README.md
documentation
This PR intends to update the README for this repository
[OSD-15452](https://issues.redhat.com//browse/OSD-15452)
_Resolves #_
[OSD-15452](https://issues.redhat.com//browse/OSD-15452)
> OSD-15452 : Updating Readme

- docs/PS1-setup.md
documentation
Update ZSH ps1 setup guide
> Update how to enable kube-ps1 plugin in Zsh

- pkg/utils/util.go
Bug
This PR fixes the logout functionality by modifying the backplane-api URL regular expression to adhere to the new backplane infrastructure.
https://issues.redhat.com/browse/OSD-15582
I've tested this locally with the new login/logout flow and it works as expected.
> OSD-15582: Fix backplane-api server regex

- cmd/ocm-backplane/console/console.go
bug
We need this PR to fix console container creation issues when console is already running.
[OSD-15495](https://issues.redhat.com//browse/OSD-15495)
> OSD-15495 - Add method to check if the container is already running

- cmd/ocm-backplane/login/login.go
- cmd/ocm-backplane/login/login_test.go
- docs/PS1-setup.md
feature 
Add ocm token to kube config file
https://issues.redhat.com/browse/OSD-15552
> OSD-15552: Add ocm-token to kubeconfig

- cmd/ocm-backplane/console/console.go
bug
Fixing empty console UI 
https://issues.redhat.com/browse/OSD-15870
> OSD-15870: Add HTTPS_PROXY env vars before init consle UI

- Dockerfile
- Makefile
- OWNERS
- docs/release.md
- golangci.yml
cleanup
Removes redundant and incorrect data from the repository
> Post migration cleanup

- Makefile
bug
Lint CI task mostly timeout after 1 min , this PR will increase timeout to 5 min
> Increase lint timeout to 5 min

- OWNERS
> add bmeng as owner

- Makefile
- cmd/ocm-backplane/console/console.go
- cmd/ocm-backplane/console/console_suite_test.go
- cmd/ocm-backplane/console/console_test.go
- go.mod
- pkg/utils/mocks/ocmWrapperMock.go
- pkg/utils/ocmWrapper.go
cleanup
Adding unit tests to console commands 
_Resolves #_
[OSD-15471](https://issues.redhat.com/browse/OSD-15471)
> OSD-15471: Add console unit tests

- OWNERS
> remove reetika in owner

- cmd/ocm-backplane/login/login.go
feature
These functions will allow downstream users of backplane to get a *rest.Config for a specific OCM cluster id and programmatically interact with the Kubernetes API of the cluster. This will allow for a more stable automation of currently toilsome tasks where users are currently left with falling back to bash and ad-hoc commands.
[OSD-16599](https://issues.redhat.com//browse/OSD-16599)
For example, this allows for:
```go
import (
bplogin "github.com/openshift/backplane-cli/cmd/ocm-backplane/login"
bpconfig "github.com/openshift/backplane-cli/pkg/cli/config"
"k8s.io/client-go/kubernetes"
metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)
func main() {
const clusterID = "blah"
bp, err := bpconfig.GetBackplaneConfiguration()
if err != nil {
panic(err)
}
restConfig, err := …
```
> Add GetRestConfig and GetRestConfigAsUser

- cmd/ocm-backplane/console/console.go
- cmd/ocm-backplane/console/console_test.go
- cmd/ocm-backplane/login/login.go
- cmd/ocm-backplane/status/status.go
- pkg/cli/config/config.go
- pkg/cli/session/session.go
- pkg/utils/clientUtils.go
- pkg/utils/cluster.go
- pkg/utils/renderingutils.go
- pkg/utils/util.go
> typo fixes and updates some of the variable names to match golang convention

- cmd/ocm-backplane/login/login.go
- cmd/ocm-backplane/login/login_test.go
cleanup
Fixes formatting of a couple error messages
_Resolves #_
> Fix formatting of a couple error messages

- cmd/ocm-backplane/cloud/cloud.go
- cmd/ocm-backplane/console/console.go
- cmd/ocm-backplane/managedJob/managedJob.go
- cmd/ocm-backplane/script/script.go
- cmd/ocm-backplane/session/session.go
- cmd/ocm-backplane/upgrade/upgrade.go
- cmd/ocm-backplane/version/version.go
> refactor: update help text

- pkg/awsUtil/sts.go
feature
Add retries to calls during the new backplane-flow assume role chain process. This will handle eventual consistency in IAM when backplane API modifies trust policies.
[OSD-16490](https://issues.redhat.com//browse/OSD-16490)
> Set up retries for assume role chain calls

- OWNERS
add more team members as reviewer
> add team thor members as reviewer

- cmd/ocm-backplane/managedJob/createManagedJob.go
- cmd/ocm-backplane/managedJob/createManagedJob_test.go
feature
Wait for job to be finished. if the wait flag specified
```
ocm backplane managedjob create SREP/example -w -p "var1=test"
Job openshift-job-aaa created.
Waiting for openshift-job-aaa  to be finished .....
Done
```
_Resolves #_
https://issues.redhat.com/browse/OSD-16604
> OSD-16604: Add managed script wait flag until the job is finished

- cmd/ocm-backplane/managedJob/createManagedJob.go
- cmd/ocm-backplane/managedJob/createManagedJob_test.go
_(feature)_
_Resolves #[OSD-16605](https://issues.redhat.com//browse/OSD-16605)_
> [OSD-16605] streaming logs for managedjob

- go.mod
cleanup
Bumping version to go 1.19
_Resolves #_
> Bumping go version to 1.19

- README.md
It instructs the user to use an updated go version so that there won't be any kube config files left after testing
_Resolves #[OSD-17636](https://issues.redhat.com/browse/OSD-17636)_
> Updated readme with instruction to users to use an updated version of go version

- README.md
documentation
As a part of [OSD-17611](https://issues.redhat.com//browse/OSD-17611), adds info on BP-CLI release cycle
[OSD-17611](https://issues.redhat.com//browse/OSD-17611)
_Resolves #_
> OSD-17611 : Adding BP-CLI release cycle info

- cmd/ocm-backplane/cloud/assume.go
- pkg/awsutil/sts.go
- pkg/awsutil/sts_test.go
feature
Adds a flag `--console` to `cloud assume` command to mimic the functionality of `cloud console` but for the new backplane flow.
_Resolves [OSD-18258](https://issues.redhat.com/browse/OSD-18258)_
> Add flag to the 'assume' command to generate a console url

- .ci-operator.yaml
- cmd/ocm-backplane/managedJob/createManagedJob_test.go
- pkg/utils/renderingutils.go
- pkg/utils/util.go
Feature
Adds a new file that indicates ProwCI which base image to consume giving the Backplane team more granular control over our CI; more specifically the go version it runs on.
> fix: add CI base image

- cmd/ocm-backplane/managedJob/createManagedJob.go
- cmd/ocm-backplane/testJob/createTestJob.go
- cmd/ocm-backplane/testJob/createTestJob_test.go
- go.mod
- go.sum
- pkg/client/mocks/ClientMock.go
- pkg/client/mocks/ClientWithResponsesMock.go
_(feature)_
- Allows users to pass in a custom base image when testing new managed scripts. 
- Depends on backplane CLI changes (https://gitlab.cee.redhat.com/service/backplane-api/-/merge_requests/301) being merged. 
_Resolves #_
> [OSD-18362] Add base image override to create testjob command

- README.md
Update the README.md adding vulnerability scanning with govulncheck
https://issues.redhat.com/browse/OSD-18938
> Updated the REAEME.md adding vulnerability scanning with govulncheck

- pkg/elevate/elevate.go
- pkg/elevate/elevate_test.go
Reverts openshift/backplane-cli#211
> Revert "OSD-18058 : Adding a new interactive shell session when we do debug with elevate command "

- OWNERS
This pr will add new members of team thor to the reviewers list for backplane
_NA_
_NA_
> Updating reviewers list

- OWNERS
For your consideration, I think I'm familiar with the repo and can help out with progress in NASA hours.
> Add mjlshen to reviewers/approvers

- OWNERS
> Add samanthajayasinghe as maintainer and approver

- pkg/cli/config/config_test.go
unit-test
Adding unit tests to backplane config 
This is an improvement of https://issues.redhat.com/browse/OSD-19188
> Add config unit tests

- .github/PULL_REQUEST_TEMPLATE.md
feature
some R's with only tests and `unit-test`  type cover those PR's
> Add unit-test type to PR template

- VERSION.md
_(feature)_
Trigger the CI release for backplane-cli
https://issues.redhat.com/browse/OSD-19314
> Trigger the release automation

- OWNERS
cleanup
Adding more reviewers and approvers to make review process faster.
_Resolves #_
> Add more approvers and reviewers

- cmd/ocm-backplane/managedJob/logsManagedJob.go
[OSD-20994](https://issues.redhat.com//browse/OSD-20994): ocm-backplane managedjob log --manager
ocm-backplane managedjob log --manager
[OSD-20994](https://issues.redhat.com//browse/OSD-20994)
_Resolves #_
> OSD-20994: ocm-backplane managedjob log --manager

- cmd/ocm-backplane/login/login.go
> Fix typo in debug message

- OWNERS
> cleanup: Update Owner

- VERSION.md
_(feature/test)_
https://issues.redhat.com/browse/OSD-20658
https://docs.google.com/document/d/1_EfS9FGuT-3a4i_1xC3jyhIh9qWrNfWMINLoe-8VhhU/edit
> Test the semi-auto way to cut a bp-cli release

- VERSION.md
_(test)_
Triggering CI release
> Update VERSION.md to trigger ci release

- ci-release.sh
_(test/feature/)_
Adding more debug info to test the ci-release script
> Adding more debug info to test the ci-release script

- VERSION.md
_(bug/feature)_
Trigger CI release for testing
> Trigger CI release

- Dockerfile
> stick oc to version 4.15

- pkg/utils/util.go
Potential suggestion for improving error handling
Some http responses fail to be parsed as JSON. In the current error handling, the json unmarshal error can be returned, 
squashing the original http info.. This can make it difficult for the end user to debug their fault as seen by our internal dialogs (ie slack "search:invalid character 'p' ", etc).  This PR provides a simple suggestion to include the HTTP response info in the returned error. 
Example err message today:
"login err:'failed to backplane login to cluster : invalid character 'p' after top-level value%"
Suggested message per PR:
"login err:'failed to backplane login to cluster : status:'404 Not Found', code:'404'; failed to unmarshal response:'404 page not found '; invalid character 'p' after top-level value%"
_Resolves #_ …
> Avoid squashing http response err info with unmarshal err

- docs/hotfix.md
documentation
Adds details on backplane hotfix process
[OSD-19437](https://issues.redhat.com//browse/OSD-19437)
_Resolves #_
> OSD-19437- Adding backplane hotfix process

- Dockerfile
bug
Fix Image tag 
_Resolves #_
> Fix dockerfile ubi image tag

- cmd/ocm-backplane/console/console.go
- cmd/ocm-backplane/console/console_test.go
What type of PR is this?
Feature
What this PR does / Why we need it?
Addresses the issue with the web console pod failing to start if it is already running in a different terminal session
Which Jira/Github issue(s) does this PR fix?
https://issues.redhat.com/browse/OSD-23459
Implemented as suggested in https://redhat-internal.slack.com/archives/C016S65RNG5/p1715785884588929
Creating this PR with a different approach as the original requested `--replace` flag is not easily implemented and can be reviewed https://github.com/openshift/backplane-cli/pull/583
> adding beforeStartCleanUp logic to cleanup console pods

- OWNERS
cleanup
Removes @cblecker and @jharrington22 from OWNERS as we are not actively reviewing PRs in this space.
> Remove cblecker and jharrington22 from OWNERS

- README.md
It will add a section for Fixing Go Version Compatibility Issues to backplane-cli
_Resolves #_
> Add a section for Go Version Compatibility issues to readme

- Dockerfile
cleanup
Remove explicit go1.23 install in the Dockerfile
_Resolves #_
> [Cleanup] Remove explicit go1.23 install in the Dockerfile

- cmd/ocm-backplane/login/login.go
- pkg/login/additional_login_detector.go
Updates the error log messages to be a bit more descriptive on what went wrong and more importantly what's NOT a problem.
- Closes #
> make the errors a bit more not-scary

- cmd/ocm-backplane/login/login.go
- pkg/login/additional_login_detector.go
- pkg/login/additional_login_detector_test.go
Additional checks if initial whoami lookup fails for some reason, with additional debugging
- Closes #
> additional check if lookup fails

- cmd/ocm-backplane/cloud/common.go
- cmd/ocm-backplane/cloud/common_test.go
Add client side IP validation and inform user if it is not allowed by the inline policy.
- Closes #
> [OSD-29413] add ip check and print warning if proxy ip is not allowed

- cmd/ocm-backplane/cloud/ssm.go
- cmd/ocm-backplane/cloud/ssm_test.go
This fixes the 
It fixes bug related to cloud ssm command which was caused after introducing the inline policy. This is majorly impacting management clusters which are following isolated backplane policy.
- Closes #[OSD-29355](https://issues.redhat.com/browse/OSD-29355)
The code will set the proxy url in your environment explicitly and will load AWS SDK configuration with the custom HTTP client
```
dmaharan@dmaharan-mac backplane-cli % ./ocm-backplane cloud ssm --node ip-10-0-0-182.ca-central-1.compute.internal
Starting session with SessionId: e4abf0bf76199710d76b3ecaa2c6f4ae-aax6husuarnuy3ffu9xu43nkrq
sh-5.1$ ps
PID TTY          TIME CMD
3014761 pts/0    00:00:00 sh
3015029 pts/0    00:00:00 ps
sh-5.1$ ls
VGAuthService                  mkfifo                     shred
'[' …
```
> OSD-29355 : Fix ssm bug which is causing for management clusters following isolated backplane flow

- cmd/ocm-backplane/cloud/common.go
This PR adds comments around the "why" we filter the trusted ip list. 
- Closes #
> Maint: add comments to clarify the filtering of trusted ips

- pkg/awsutil/sts.go
This helps knowing which account to check for potential issues.
- Closes #
> Add logging to show which role is being assumed right now.

- OWNERS
Adding Shawn to the maintainers group
- Closes #
> Adding Shawn to the maintainers group :tada: 

- cmd/ocm-backplane/cloud/common.go
- cmd/ocm-backplane/cloud/common_test.go
This is related to https://issues.redhat.com/browse/SREP-637. 
This PR is to improve error messages when bp-cli fails due to different reasons. The list of points are below:
In the first part I am addressing the first two bullet points
- VPN IP's are not whitelisted in payer/jump-account AWS policies 
- SRE user name not included in payer/jump-account AWS policies
- AWS sts connection issues
We need this PR as it creates lots of confusion and misunderstanding when it comes to troubleshooting user issue that are related to the backplane console.
> [SREP-637]: improve backplane cloud console error messages
