.gitignore
.goreleaser.yaml
Makefile
docs/release.md

This PR aims to automate `openshift/backplane-cli` repository's release process by leveraging goreleaser.
<hr>
Resolves: [OSD-14993](https://issues.redhat.com/browse/OSD-14993)

OSD-14993: Automate backplane-cli release cycle

---

cmd/ocm-backplane/root.go
cmd/ocm-backplane/upgrade/upgrade.go
go.mod
go.sum
internal/github/github.go
internal/github/github_test.go
internal/github/options.go
internal/upgrade/options.go
internal/upgrade/upgrade.go
internal/upgrade/writer.go
pkg/info/info.go

This PR introduces `ocm backplane upgrade` command that based on GitHub latest release 
```
$ ocm backplane upgrade
? A newer version "v0.0.1" is available.
Would you like to upgrade? (y/N)
```

OSD-14677: Added backplane-cli upgrade based on the latest version

---

cmd/ocm-backplane/cloud/cloud.go
cmd/ocm-backplane/cloud/cloud_suite_test.go
cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/console_test.go
cmd/ocm-backplane/cloud/credentials.go
cmd/ocm-backplane/cloud/credentials_test.go
cmd/ocm-backplane/root.go
go.mod
go.sum

This PR adds the following things to backplane cli 
* Add cloud console command 
```
ocm backplane cloud console <cluster-id>
```
* Add cloud credentials command 
```
ocm backplane cloud credentials <cluster-id>
```
[OSD-14684](https://issues.redhat.com/browse/OSD-14684)

OSD-14684: Add Backplane cloud console and credentials commands

---

pkg/info/info.go
pkg/utils/cluster.go
pkg/utils/cluster_test.go
pkg/utils/ocmWrapper.go
pkg/utils/util_test.go

_(feature)_
This pull request replaces the call to get the backplane host from the hive shard with a call to `GetBackplaneURL()`. This removes the dependency on `ocm backplane tunnel`. 
If the environment variable isn't set, or the path to the config file does not exist or is invalid, it shows an error. 
If those are valid, it uses that configuration file or environment variable as the program's `BACKPLANE_URL`. 
_Resolves [OSD-14678](https://issues.redhat.com/browse/OSD-14678)_

Deprecate tunnel call in cluster.go and add BACKPLANE_CONFIG environment variable

---

cmd/ocm-backplane/login/login.go

feature
Add check for env KUBE_PS1_CLUSTER_FUNCTION 
[OSD-14331](https://issues.redhat.com//browse/OSD-14331)
- [ Yes] Ran unit tests locally
- [Yes ] Validated the changes in a cluster
- [ No] Included documentation changes with PR

Added check for env KUBE_PS1_CLUSTER_FUNCTION

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/utils/mocks/ocmWrapperMock.go
pkg/utils/ocmWrapper.go

Feature 
This change introduces an optional `--manager` flag to ocm backplane login which will cause the CLI to look up the cluster's "managing" cluster (either a Hive shard, or a Hypershift Management Cluster) and log in to that instead.
Note that this change will not work for Hive-based clusters in Staging/Integration environments, as their managing cluster exists in a different environment. (however, this is not a problem for Hypershift clusters)
This change also fixes some small formatting issues in the existing `login.go` (code indented unnecessarily).

Add flag to login to managing cluster instead of target cluster

---

README.md
cmd/ocm-backplane/elevate/elevate.go
cmd/ocm-backplane/root.go
pkg/elevate/elevate.go
pkg/elevate/elevate_test.go

_(feature)_
This pull request add the ability to elevate to `backplane-cluster-admin` using `ocm-backplane`, as well as adding an optional `ElevationReason` to the Kube API request in-place. 
This makes audit tracking and resolving compliance tickets easier, reducing the burden on on-call developers, managers, and users of backplane. 
Usage: 
`ocm backplane elevate <reason-string> <command>`
`ocm backplane elevate 'Getting pods in all namespaces' -- get po -A`. 
`--as backplane-cluster-admin` is added to end the request, which is sent to `os.Exec`. A new temporary kubeconfig with the `impersonation.user-extra` property "elevationReason"=<reason> is then created. A new temporary role is created (and the old one deleted) that allows adding this extra field to the API HTTP request (see …

Add elevate command

---

pkg/utils/util.go

Follows up on https://github.com/openshift/backplane-cli/pull/44

OSD-15582: Make backplane-api server regex loosely restricted

---

cmd/ocm-backplane/script/listScripts.go
cmd/ocm-backplane/script/listScripts_test.go

Bug
When a user does not have any script listed for them, Backplane CLI throws a vague error which is bad user experience. This PR fixes the issue.
[OSD-15550](https://issues.redhat.com//browse/OSD-15550)

OSD-15550 - Add error handling and unit test for empty list of scripts

---

pkg/utils/util.go

Bug
It was assumed that all Backplane API URLs will be in the form of `api.{env}.backplane.{openshift|devshift}.{com|net}` but the production URL doesn't specify the OCM environment in it (`api.backplane.openshift` ).
This PR tweaks the bp-api regex to conform to the same.

Tweak regex to conform to prod URL

---

cmd/ocm-backplane/login/login.go

bug
write proxy-url to kubeconfig after login
_Resolves #_

Bug fix: proxy-url not exists after login

---

.goreleaser.yaml
cmd/ocm-backplane/version/version.go
internal/github/github.go
internal/github/github_test.go
internal/upgrade/upgrade.go
pkg/info/info.go

Bug
This PR fixes how we fetch binaries for upgrades and well as enforces the `version` of backplane CLI to not be static.
https://issues.redhat.com/browse/OSD-15761
- The `version` is not static anymore and is populated by goreleaser's build dynamically upon each release based on tags.
- Run a goreleaser local build: `goreleaser build --skip-validate`. This will generate the release artifacts in the `dist/` folder.
- Run the newly generated binary: `./dist/ocm-backplane_linux_amd64_v1/ocm-backplane upgrade` or `./dist/ocm-backplane_linux_amd64_v1/ocm-backplane version`.

Fix upgrade and version check

---

pkg/cli/config/config.go
pkg/cli/config/config_test.go
pkg/info/info.go

Bug
- Adhere to configuration file naming on UNIX systems.
- Refrain the use of `os.UserConfigDir()` to fetch the configuration file path as in Darwin (MacOS), it returns `$HOME/Library/Application Support` instead of `$HOME/.config`.

Change config file name

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
cmd/ocm-backplane/login/login.go
go.mod
internal/github/github.go

cleanup
[OSD-16175](https://issues.redhat.com//browse/OSD-16175)
As SREs are switching to the new backplane-cli, sometimes they get a confusing error message:
```
2023/04/27 11:52:41 getting AWS credentials from backplane-api
2023/04/27 11:52:42 can't find backplane url: %!w(<nil>)
```
The message comes from the following block of code when there there is no error, but the format string attempts to insert one:
```go
if err != nil || bpConfig.URL == "" {
return fmt.Errorf("can't find backplane url: %w", err)
}
```
This PR attempts to address it by returning this instead:
```go
if bpConfig.URL == "" {
return errors.New("empty backplane url - check your backplane-cli configuration")
}
```

Improve error message clarity when the backplane url is empty

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go

cleanup
Currently, when we try to login to a cluster that is hibernating, it tries for 30 seconds before returning an error. This PR checks right away so we can give faster feedback since a login should never work for a hibernating cluster.
```
❯ time ocm backplane login ${HIBERNATING_CLUSTER}
INFO[0000] Target cluster                                ID=${ID} Name=${NAME}
ERRO[0030] cluster ${NAME} is hibernating, login failed 
ocm backplane login ${HIBERNATING_CLUSTER}  0.07s user 0.08s system 0% cpu 30.949 total
```
[OSD-16184](https://issues.redhat.com//browse/OSD-16184)

Give faster feedback when logging into hibernating clusters

---

README.md
cmd/ocm-backplane/testJob/createTestJob.go
cmd/ocm-backplane/testJob/createTestJob_test.go
cmd/ocm-backplane/testJob/getTestJobLogs.go
cmd/ocm-backplane/testJob/testJob.go

_feature_
- Allows us to import bash libraries into managed scripts, and test them using test jobs. 
It does this by finding the file and inlining the function into the script itself. 
For a managed script example.sh:                           
```
---                                                        
#!/bin/bash                                                
source /managed-scripts/libs/lib.sh                        
echo_foo "Hello"                                           
---                                                        
```                                                  
And function /managed-scripts/libs/lib.sh                  
```
---                                                        
#!/bin/bash                                                
function …
```

Add ability to use libraries with test jobs

---

README.md
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/root.go
cmd/ocm-backplane/session/session.go
pkg/cli/config/config.go
pkg/cli/session/session.go
pkg/cli/session/session_suite_test.go
pkg/cli/session/session_test.go
pkg/info/info.go
pkg/login/kubeConfig.go

feature
```
ocm backplane session test-session -c <cluster-id>
Setting up environment...
INFO[0002] Target cluster                                ID=<cluster-id>
[test-session (<cluster-info-PS1>)]$
```
you can directly login via cluster id 
```
ocm backplane session <cluster-id>
Setting up environment...
INFO[0002] Target cluster                                ID=<cluster-id>
[test-session (<cluster-info-PS1>)]$
```
```
ocm backplane  session --delete test-session 
Cleaning up Backplane session test-session
```
```
[ <session-alias-orcluster-id> (<cluster-info-PS1>]$ history 
1  2023-05-08 15:06:05 oc get nodes
2  2023-05-08 15:06:13 oc get co
3  2023-05-08 15:06:40 history 
```
By default all session will save into ~/backplane directory 
You can change the dir path via config 
```
{ …
```

OSD-16162: Add Backplane Session command

---

README.md
cmd/ocm-backplane/config/config.go
cmd/ocm-backplane/config/get.go
cmd/ocm-backplane/config/set.go
cmd/ocm-backplane/root.go
pkg/cli/config/config.go

Feature
This PR adds a new `config` command to Backplane CLI making configuration management easy.
- `ocm backplane config get [url/proxy-url/all]` retrieves the Backplane CLI configuration variables.
- `ocm backplane config set url https://example.com` sets the Backplane CLI configuration.
Uses [viper](https://github.com/spf13/viper) in the backend.
Resolves: https://issues.redhat.com/browse/OSD-15878
Unit tests will be followed with another PR

Config subcommand

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/login/login.go
pkg/utils/util.go

feature
In order to help users identify version related issue faster, this PR adds a warning message when they attempt to login to a cluster.
[OSD-14573](https://issues.redhat.com//browse/OSD-14573)

OSD-14573-warn-user-for-old-cli

---

.golangci.yml
cmd/ocm-backplane/cloud/credentials_test.go
cmd/ocm-backplane/testJob/createTestJob_test.go
pkg/elevate/elevate_test.go
pkg/monitoring/monitoring.go

_(bug)_
Update the golangci config file name, and enable some linters by default
_Resolves #_

fix the golangci yml name

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/cli/config/config.go
pkg/cli/config/config_test.go

feature
Check the API connection via HTTP proxy transmission and provide a proper error message to the end user 
[OSD-15841](https://issues.redhat.com//browse/OSD-15841)
- [] Included documentation changes with PR

OSD-15841: Check proxy and API connection if login failed

---

cmd/ocm-backplane/cloud/assume.go
cmd/ocm-backplane/cloud/cloud.go
cmd/ocm-backplane/cloud/token.go
go.mod
go.sum
pkg/awsUtil/credentials.go
pkg/awsUtil/credentials_test.go
pkg/awsUtil/sts.go
pkg/awsUtil/sts_test.go
pkg/client/mocks/ClientMock.go
pkg/client/mocks/ClientWithResponsesMock.go
pkg/utils/jwt.go
pkg/utils/jwt_test.go

feature
Adds one command to fetch STS credentials for given role, and another to assume a chain of roles from a starting point to a cluster's account
[OSD-16489](https://issues.redhat.com//browse/OSD-16489)
[OSD-16490](https://issues.redhat.com//browse/OSD-16490)
Waiting on [OSD-16494](https://issues.redhat.com//browse/OSD-16494) to finish
To test locally:
In an AWS account, create a role with the trust policy in the attached ticket. Run this command with the arn for that role passed in as --role-arn, i.e. backplane cloud token --role-arn [role arn]. If successful, the command should output AWS STS Credentials as a JSON payload.

Add commands to get an STS token for a role from an ocm token, and to assume roles through a chain of ARNs

---

cmd/ocm-backplane/login/login_test.go
pkg/utils/ocmWrapper.go

bug
Users can't log into hive cluster if the hive cluster not belong to same ocm env 
_Resolves #_ [OSD-16244](https://issues.redhat.com//browse/OSD-16244)

OSD-16244: Add error message if management cluster is not belong to same ocm env

---

cmd/ocm-backplane/root.go
cmd/ocm-backplane/root_suite_test.go
cmd/ocm-backplane/root_test.go
pkg/cli/globalflags/logs.go

bug
Showing warning level as default log level
All commands shows error as follows 
```
ocm backplane <sub-command>  ( shows warn logs )
ocm backplane -v <sub-command>  ( shows info logs )
ocm backplane -v=<log-level> <sub-command>  ( shows <log-level> logs )
```
_Resolves #_https://issues.redhat.com/browse/OSD-17209

OSD-17209: Update backplane cli commands default to warning log level

---

cmd/ocm-backplane/session/session.go
pkg/cli/session/session.go

Feature
This adds the same `--service` and `--manager` flags to `ocm backplane session` that are already in place for `ocm backplane login` in order to establish a backplane session to the cluster's service or management cluster respectively.
I use `backplane session` almost exclusively these days, but I miss these flags from `backplane login` quite a lot.

Add service and manager flags to backplane session

---

README.md
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
cmd/ocm-backplane/session/session.go
pkg/cli/globalflags/globalflags.go

Feature
This PR makes the `manager` and `service` flags global so multiple commands can access it while maintaining flag consistency.
Please test this locally before you merge

Refactor: Make manager & service flags global

---

cmd/ocm-backplane/login/login_test.go
pkg/cli/config/config.go

OSD-17374: Fixed backplane error overwriting issue when the proxy is not available

---

cmd/ocm-backplane/script/describeScript.go
cmd/ocm-backplane/script/describeScript_test.go
cmd/ocm-backplane/script/listScripts.go
cmd/ocm-backplane/script/listScripts_test.go

Feature (changing command to use new API)
Changing API calls to use GetScriptsByCluster instead of GetScripts due to a bug for two comannds:
- describe
- list
The API call semantic is the same but with added `clusterId` in the API call.
Furthermore, clusterKey to clusterId transformation and loading from config file added.
Provided unit tests modified in accordance with the new behavior.
Resolves [OSD-12531](https://issues.redhat.com/browse/OSD-12531)
Tests were modified as the expected behavior changed.

OSD-12531: Replacing GetScripts with new GetScriptsByCluster API calls

---

cmd/ocm-backplane/session/session.go
pkg/cli/session/session.go
pkg/cli/session/session_test.go

Bug
PR #148 moved the `--manager` and `--session` flags to global options, but these do not get set in `backplane session` when used. This is because the `session`'s internal options boolean variables are separate to those in the `globalOpts` struct, so they're never going to get set to what gets set in `globalOpts`.
The fix is straightforward, just add the global opts to `session`'s own options struct as a pointer.

Fix usage of global opts in backplane session

---

cmd/ocm-backplane/cloud/credentials.go

bug
Fixes nil ptr dereference when getting cloud credentials.
Steps to reproduce:
- run `ocm backplane cloud credentials <clusterid>` without running proxy connection
_Resolves #_

fix: nil pointer dereference when getting cloud credentials

---

cmd/ocm-backplane/cloud/assume.go
cmd/ocm-backplane/cloud/assume_test.go
cmd/ocm-backplane/cloud/cloud.go
cmd/ocm-backplane/cloud/credentials.go

feature
Adds the ability to manually provide the role assume sequence to the `cloud assume` command. This is intended to allow test of changes in stage and integration environments.
[OSD-17196](https://issues.redhat.com//browse/OSD-17196)

add --debug-file flag for 'cloud assume' command

---

Makefile
go.mod
go.sum

_feature_
It scans the code and dependencies against known security vulnerabilities.
_Resolves_ #[OSD-17895](https://issues.redhat.com/browse/OSD-17895)  
I ran `govulncheck./...` in go version 1.21.0 and fixed the vulnerabilities. If you'll install gvulncheck and check it using some lower version of go then you might get lots of compatible issues which will eventually mess up `go.mod` and `go.sum` file.

Add govulnerability check to bp-cli

---

Makefile

_bug_
This PR will help in running govulncheck in the systems where govulncheck binary is not present. 
_Resolves #[OSD-18227](https://issues.redhat.com/browse/OSD-18227)_

Check Govulncheck binary present or not

---

cmd/ocm-backplane/testJob/createTestJob.go

bug
For testjob having library import, the current workflow will wrap the library file into a string, use a cat command to put the library content to lib.sh inline, then replace the `source /path/to/lib.sh` to `source ./lib.sh`
In some cases, the `cat << EOF` may cause strange issues if the library content has special characters or special formats. For example, the lib in https://github.com/openshift/managed-scripts/pull/137 may result in error `unbound variable`.
This PR encode the library file to base64, and decode the file inline, so that we don't need to worry about the format inside the library. 
We can use the existing `lib-sourcer` example for testing, the behavior remains unchanged.
```
[managed-scripts/scripts/examples/lib-sourcer] $ ocm.stg backplane testjob logs …
```

TestJob to use base64 for library import

---

docs/PS1-setup.md

The export keyword was missing from the setup of kube-PS1 for ZSH which was causing the following warning anytime while logging into the cluster
```
WARN[0007] Env KUBE_PS1_CLUSTER_FUNCTION is not detected. It is recommended to set PS1 to learn which cluster you are operating on, refer https://github.com/openshift/backplane-cli/blob/main/docs/PS1-setup.md
```
Also the method mentioned in the docs for ZSH would work only when oh-my-zsh is added/enabled separately in zsh. I have added the process to enable this for vanilla zsh
_Resolves #_

Updated PS1 Setup to work with ZSH

---

Makefile

workaround
This PR modifies the `scan` target in the Makefile. If `govulncheck` detects any vulnerabilities, it will display a notification message but will still return a successful exit code, ensuring that the `ci/prow/scan-optional` CI job passes.
Even though `govulncheck` will continue to run, any detected vulnerabilities will be recorded in the `CI build logs`. This allows us to keep track and plan for the necessary updates to the vulnerable Go library packages at a later time.

[OSD-18938] Workaround the CI failed for govulncheck

---

cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/console/console_test.go

bug
When using the `--image` flag on a non `linux/amd64` platform, the pull/run will fail due to a platform/architecture mismatch. This comes up in particular when running on an arm64 based mac with podman.
This forces the `--platform linux/amd64` flag on all podman image pulls. If you're running on a linux/amd64 platform, then this is a noop. But if you are using podman for mac, this will ensure you are always running the linux/amd64 version of the console image.
_Resolves #_

When specifying image on macOS, force linux/amd64 platform

---

cmd/ocm-backplane/cloud/assume.go
cmd/ocm-backplane/cloud/assume_test.go
cmd/ocm-backplane/cloud/token.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go
pkg/cli/config/config.go

feature/bug fix
The retry mechanism built into the `sts.Client` from the AWS SDK doesn't properly handle issues of IAM updates requiring a few seconds to resolve, so we have to roll our own retry that recreates the client on every failure. See https://github.com/aws/aws-sdk-go-v2/issues/2332
[OSD-18992](https://issues.redhat.com//browse/OSD-18992)

Implement retry for eventual consistency in IAM updates

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go

_bug_
Changes for the new flow made it so that "region" wasn't being set when requesting credentials for old and new clusters, or a console link for new clusters.
_Resolves OSD-19492_

Make sure region is always present for credentials and console links

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
pkg/awsutil/sts.go

Hotfix for incident itn-2023-00143
Steps taken to test:
1. On a cluster that was known to be affected by this incident, run `ocm backplane cloud console` and `ocm backplane cloud credentials`
2. See that the isolated flow was attempted, failed, and fell back to the old flow as evidenced by a message printed to the console.
3. Take a new cluster that should in fact be using the new flow, run `ocm backplane cloud console` and `ocm backplane cloud credentials`
4. See that the isolated flow was attempted and succeeded without falling back to the old flow.

fall back to old flow if new flow fails

---

cmd/ocm-backplane/managedJob/createManagedJob.go

_feature_
To have bp-cli enabled to consume the warning header from bp-API's response, so that, when running managed-script with `ocm-backplane`, it can post warnings if the `clusterVersions` is not specified in the metadata.yaml but still allow the script continue execute.
It's interdependent with the [MR-303](https://gitlab.cee.redhat.com/service/backplane-api/-/merge_requests/303)

[OSD-19019] Enable bp-cli to consume warning header from bp API's response

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go
cmd/ocm-backplane/cloud/console_test.go
cmd/ocm-backplane/cloud/credentials.go
cmd/ocm-backplane/cloud/credentials_test.go
pkg/credentials/aws.go
pkg/utils/cluster.go
pkg/utils/mocks/ClusterMock.go
pkg/utils/ocmWrapper.go

bug/feature
This functionality was originally added in #66, but was mistakenly removed in #237
Since we are now required to pass AWS calls through a proxy, this PR adds additional logic to ensure the aws-sdk-go-v2 client returned by this function enforces the use of the provided proxy_url in a user's backplane config file.
[OSD-19711](https://issues.redhat.com//browse/OSD-19711)
This is semi-urgent to merge+release because osdctl builds an aws-sdk-go-v2 client using this function https://github.com/openshift/osdctl/blob/1b906de67017e15057a6312d698ac28565250941/pkg/osdCloud/aws.go#L182-L190 pinned on an older version where it still exists: https://github.com/openshift/osdctl/blob/1b906de67017e15057a6312d698ac28565250941/go.mod#L38 so SRE's using commands like `osdctl network …

Reimplement a way to retrieve an aws-sdk-go-v2 config from backplane

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
pkg/awsutil/sts.go

bug
Currently, the STS client tries to build from a default config. This causes the client to believe it should be an authenticated client, however unless someone exports AWS credential in their terminal, there won't be any credentials present. This PR removes the creation of an authenticated client as it is not needed, and instead creates a bare minimum config with only the necessary properties to create the STS client we need.
Resolves https://issues.redhat.com/browse/OSD-19733

Use unauthenticated STS client for assuming payer account role

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go
cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
pkg/utils/clientUtils.go
pkg/utils/mocks/clientUtilsMock.go

feature
This PR allows passing an ocm token to create an AWSV2 config, as we don't always have an offline token as ENV var/config file. 
This is needed because CAD uses client-id and client-secret to authenticate, and generates a token on the fly, this PR allows it to pass a token directly.
Needed for https://issues.redhat.com/browse/SDE-3276
_Resolves #_

feat: allow creating aws config with a custom ocm token

---

pkg/awsutil/sts.go

bug
The `fmt.Println` log message per default interferes with the `-o env`. This PR changes the `Resolving...` output to use the logger which won't affect the below:
```
export $(ocm backplane cloud credentials $CLUSTER_ID -o env)
bash: export: `resolve...': not a valid identifier
```
_Resolves #_

fix: use logger for iam changes log message

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go
cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
cmd/ocm-backplane/cloud/credentials_test.go
cmd/ocm-backplane/config/get.go
cmd/ocm-backplane/config/set.go
cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/login/login.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go
pkg/cli/config/config.go
pkg/cli/config/config_test.go
pkg/credentials/aws.go
pkg/monitoring/monitoring.go
pkg/utils/clientUtils.go
pkg/utils/mocks/clientUtilsMock.go
pkg/utils/mocks/ocmWrapperMock.go
pkg/utils/ocmWrapper.go

cleanup
We need the proxy to be configurable for programmatic access. Beyond that, this PR also allows passing the whole necessary configuration to create an AWSV2Config, instead of picking up config chunks through ENVs and external config files. 
Needed for https://issues.redhat.com/browse/OSD-19388\
_Resolves #_
**After these changes I tested the following:**
Old flow:
- ocm backplane cloud credentials
- ocm backplane cloud console
Non STS clusters:
- ocm backplane cloud credentials
- ocm backplane cloud console
New flow:
- ocm backplane cloud credentials
- ocm backplane cloud console

feat: make proxy configurable

---

OWNERS

Adding myself as reviewer/approver for EMEA as I feel I have a solid enough knowledge of the repository with my latest contribution(s).

Add typeid as review/approver

---

README.md
pkg/login/kubeConfig.go

feature
When using login --multi, the output cannot be sourced directly.
With this change we will be able to run:
```
source <(ocm-backplane login multi xxx)
```
_Resolves #_
- [ x] Validated the changes in a cluster
- [ x] Included documentation changes with PR

Allow to source --multi output

---

cmd/ocm-backplane/console/console.go
pkg/cli/config/config.go
pkg/info/info.go

bug
Since 4.14, the `monitoring-plugin` is required to be run locally. The plugin is running in cluster as a service so port forwarding is the only way to access it otherwise.
This PR sets up the locally running backplane console to include a locally running `monitoring-plugin` container in it's network and access it via a `nginx` server. The serer is pre-set in the `monitoring-plugin` container so we don't have other ways to access it.
This does not change the behavior for pre-4.14 clusters. It only adds the new container when the cluster is 4.14 and above.
[OSD-19779](https://issues.redhat.com//browse/OSD-19779)
This PR introduces a temporary nginx configuration and a function to run monitoring-plugin in a separate local container.
This change only takes effect on cluster with version …

OSD-19779 Use local monitoring plugin on 4.14+ clusters

---

cmd/ocm-backplane/console/console.go

bug
This PR fixes a mounting problem for nginx configuration on MacOS
Ref: https://stackoverflow.com/questions/73876281/rootless-podman-use-nfs-mount
[OSD-19779](https://issues.redhat.com//browse/OSD-19779)

OSD-19779 - Fix nginx configuration mounting issue for MacOS

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/cli/session/session.go
pkg/ocm/mocks/ocmWrapperMock.go
pkg/ocm/ocmWrapper.go

_(feature)_
It prints the cluster related namespaces when login with the `--manager` option, since user may like to investigate the resources within
_Resolves #OSD-19081_

print the related namespace when login via manager cluster

---

cmd/ocm-backplane/login/login.go

feature
When we use GetRestConfigAsUser (eg in osdctl) we cannot specift a reason for the elevation.
_Resolves #_
- [ na] Validated the changes in a cluster
- [ na] Included documentation changes with PR

[OSD-20024] Allow GetRestConfigAsUser with elevationReason

---

cmd/ocm-backplane/login/login_test.go

_test_
followup of #294
_Resolves #_
- [ na] Validated the changes in a cluster
- [ na] Included documentation changes with PR

[OSD-20024] Add test case for GetRestConfigAsUser

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go

_(cleanup)_
With the previous changes, the `backplaneConfiguration` should always have the URL value set, if not, it will return with error earlier.

[OSD-19188] remove the backplane url checks from cloud subcommands

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go

feature
If we are dealing with an HCP cluster, there is no reason to call OCM to determine which flow to use. All HCP clusters must be on the new flow.
[OSD-20257](https://issues.redhat.com//browse/OSD-20257)

Always use isolated flow for HCP clusters

---

pkg/login/kubeConfig.go
pkg/login/kubeConfig_test.go

bug
Without this change, when using login --multi on a cluster where we already did it, but where credentials expired, the connection will not work.
Resolves #[OSD-20017](https://issues.redhat.com//browse/OSD-20017)
- [ x] Validated the changes in a cluster
- [na ] Included documentation changes with PR

[OSD-20017] create config file with login --multi even if target config file exists

---

cmd/ocm-backplane/cloud/common.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go

feature
backplane-cli passes the SRE's email address as a role session name when assuming a customer's support role. We should not pass any SRE usernames to a customer when assuming into their account.
https://issues.redhat.com/browse/OSD-19901

Use md5 hash as role session name when assuming into customer's support role

---

ci-release.sh

_(feature)_
Update the `ci-release.sh` script to add a version comparison mechanism.  If the tag already exists, the new script aborts the release process, thereby preventing the re-release of an existing version.
https://issues.redhat.com/browse/OSD-19314

[OSD-19314] - Update the bp-cli release script to add version comparison mechanism

---

cmd/ocm-backplane/cloud/common.go

feature
It can still be supplied in the config file as an override, but with this change it is now optional for individuals interacting with standard OCM URLs.
[OSD-20606](https://issues.redhat.com//browse/OSD-20606)

Detect assume-initial-arn from OCM URL

---

pkg/ocm/ocmWrapper.go

Bug
There are edge case scenarios where a user doesn't have enough permissions such as the BackplaneCLI OCM role to fetch the ClusterService Environment Resource from OCM CS.  This results in Backplane CLI abruptly timing out with a connection error message. This PR is an aim to address it from a UX perspective.
https://issues.redhat.com/browse/OSD-20675

Log relevant message when a user isn't able to fetch the API URL

---

cmd/ocm-backplane/config/troubleshoot.go
cmd/ocm-backplane/config/troubleshoot_test.go
pkg/cli/config/config.go
pkg/cli/config/config_test.go

Resolves: https://issues.redhat.com/browse/OSD-19785

Add multiple proxy support to Backplane configuration

---

pkg/elevate/elevate.go

bug
When we call RunElevate, it overrides the definition of KUBECONFIG variable to a temporary file which is then deleted, which makes following kube commands to fail as there is no more configuration defined
_Resolves #[OSD-21061](https://issues.redhat.com//browse/OSD-21061)
Once this will be implemented and delivered, osdctl will be updated to remove hack (https://github.com/openshift/osdctl/pull/515)
- [ x] Validated the changes in a cluster
- [ na] Included documentation changes with PR

Do not override KUBECONFIG when RunElevate

---

Dockerfile

_(bug)_
To modify the awk command to exclude the rhel-specific binary to avoid curl resolving issues
To fix the curl resolving issue in prow job
[SLACK THREAD for more context](https://redhat-internal.slack.com/archives/C016S65RNG5/p1709249252551559?thread_ts=1709147482.559129&cid=C016S65RNG5)

Modify the awk command to exclude the rhel-specific binary

---

cmd/ocm-backplane/console/console.go

bug
This fixes a bug where if `ce.putFileToMount` encountered an error, it wouldn't be passed through. This resulted in a situation where the monitoring plugin wouldn't start, but no error would be passed (even with debug).
It also fixes the root bug that was causing `ce.putFileToMount` to fail. The `podman machine ssh` command requires the name of the machine you are SSH'ing into to be specified if you are putting an in-line command command.
_Resolves #_

Fix monitoring-plugin on podman

---

cmd/ocm-backplane/testJob/createTestJob.go

Bug
The current `backplane testjob create` will import the library by encode&decode it to `./lib.sh`.
The `./` directory is `/root` which doesn't have sufficient permission for the script to write a `./lib.sh` file. 
This PR changes it to `/tmp/lib.sh` to fix the permission issue.
Reproducer:
- Create a test script, which has a line:
```
source /managed-scripts/lib/sftp_upload/lib.sh
```
- Run `ocm backplane testjob create`, then check the log.
- It will show error:
```
❯ ocm backplane testjob logs openshift-job-dev-xn9qz   
/bin/bash: line 14: ./lib.sh: Permission denied
```
Changing to `/tmp/lib.sh` can solve the problem.
_Resolves #_

Use tmpdir for testjob to import lib

---

cmd/ocm-backplane/login/login.go
pkg/login/kubeConfig.go

feature
This commit adds some more detailed debug printouts for the ocm-backplane login command, the printouts could be used by using  --verbosity=debug.
e.g 
```
./ocm-backplane --verbosity=debug login <cluster identification>
```
[OSD-19615](https://issues.redhat.com/browse/OSD-19615)
_Resolves #_
- X Ran unit tests locally
- X Validated the changes in a cluster

OSD-19615: Enhance backplane-cli verbose messages for login subcommand

---

cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/console/console_test.go
cmd/ocm-backplane/console/console_tests_util.go
go.mod

unit-test
This adds a series of unit tests for the console.go file
[OSD-20030](https://issues.redhat.com/browse/OSD-20030)
_Resolves #_
There has been a long standing issue with unit testing the console.go file, this commit adds a series of tests and some minor changes to console.go to ensure the use of mock interfaces for testing.

Adding Backplane Console tests

---

cmd/ocm-backplane/login/login.go

bug fix
> ERRO[0003] invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
Fixes login via PagerDuty incident link or ID.
[#368](https://github.com/openshift/backplane-cli/pull/368)

fix: Include condition to check if arg pd is empty

---

pkg/cli/config/config.go

Bug
PD token config missing warning shows when users login to the cluster 
https://issues.redhat.com/browse/OSD-21670

OSD-21670: Reduce verbosity level of pd-token config

---

cmd/ocm-backplane/testJob/createTestJob.go
cmd/ocm-backplane/testJob/createTestJob_test.go
go.mod

_feature_
Currently, we have the ocm backplane testjob command to test the script with custom image, but it has to be run under the script dir
Add the new parameter to specify the source dir for the script
_Resolves #_

make the testjob source dir configurable

---

cmd/ocm-backplane/cloud/common.go

feature
See https://docs.google.com/document/d/1hFlKGy2tInRJwWA28TYEsrTri4CwebVR7TdsG6LmObI/edit
[OSD-20300](https://issues.redhat.com//browse/OSD-20300)

Use md5 hash for session name when assuming Org Role in new backplane flow

---

Dockerfile

bug
This PR will fix the failed build `ci/prow/images `  :
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_backplane-cli/386/pull-ci-openshift-backplane-cli-main-images/1775807436830019584 
https://issues.redhat.com/browse/OSD-22036

Update dockerfile to exclude all arch binaries

---

cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/console/console_test.go

bug
Fixing the console container cleanup issues for both docker and podman CRI
https://issues.redhat.com/browse/OSD-21419

OSD-21419: Fixed console container cleanup issues

---

pkg/utils/shell_test.go

_(unit-test)_
Write test cases using BDD framework gingko
[OSD-21348](https://issues.redhat.com//browse/OSD-21348)
_Resolves #_

[OSD-21348] Add Test Cases for Helper Function of elevate cmd

---

README.md
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
docs/PS1-setup.md
docs/design.md

- feature
- documentation
- unit-test
As a SRE, I want backplane login to prompt for a  default namespace for me to run commands like oc debug node/xxx.
_Resolves #_[OSD-19729](https://issues.redhat.com//browse/OSD-19729)
Once merged,  `./ocm-backplane login --help`  will display                                                                                                                                                                          
```
Running login command will send a request to backplane api
...
Usage:
ocm-backplane login <CLUSTERID|EXTERNAL_ID|CLUSTER_NAME|CLUSTER_NAME_SEARCH> [flags]
...
Flags:
-n,  --namespace string   Sets a default namespace for SRE to run commands like oc debug node/xxx
...  
Example: 
Considering cluster name as asathe-19729     
- Without options …
```

OSD-19729: Enables ocm backplane login to provide  default namespace as an argument

---

pkg/cli/config/config.go

_(bug)_
https://redhat-internal.slack.com/archives/G01DC1VRAGK/p1713328523405079?thread_ts=1713327968.217359&cid=G01DC1VRAGK

Increase the timeout to get working proxy url

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go

_bug_
This will list the correct namespace when logging into the cluster's management cluster
_Resolves_ #[OSD-21691](https://issues.redhat.com/browse/OSD-21691)
Checked in a HCP staging cluster:
OCM Get:
Before Change:
After adding domain-prefix:

OSD-21691 : Add domain prefix in place of cluster name for cluster namespace

---

cmd/ocm-backplane/cloud/common.go

_(feature)_
Remove fallback to old flow in backplane-cli and return the error
https://issues.redhat.com/browse/OSD-21438

[OSD-21438] Remove the fallback to old flow

---

pkg/elevate/elevate.go
pkg/elevate/elevate_test.go

_bug_
_ref [OSD-22522](https://issues.redhat.com//browse/OSD-22522)_
When running ocm backplane elevate with args containing single/double quotes, those args are not managed properly. Here is an exemple:
```
$ ocm-backplane elevate test -- -n openshift-operator-lifecycle-manager patch deployment packageserver \  
--type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "xxx"}]' \  
-o yaml --dry-run=client
error: unable to parse "[{op:": yaml: line 1: did not find expected node content
ERRO[0000] exit status 1 
```
_Resolves #[OSD-22522](https://issues.redhat.com//browse/OSD-22522)_
With this change, we can now use args with quotes as we can see here:
```
$ ./ocm-backplane elevate test -- -n openshift-operator-lifecycle-manager patch deployment …
```

OSD-22522 elevate allows args with quotes

---

cmd/ocm-backplane/cloud/common.go

Reverts openshift/backplane-cli#402 for the reported bug.
More context: https://redhat-internal.slack.com/archives/C016S65RNG5/p1714510502957039

Revert "[OSD-21438] Remove the fallback to old flow"

---

cmd/ocm-backplane/cloud/common.go

cleanup
Currently the bp-cli falls back to the old flow if it fails to assume cloud credentials/console access with the new flow. This was a good fallback initially, but at this point it masks legitimate errors and prevents SREs from knowing what's wrong. This PR removes that fallback in place of passing along logs.
[OSD-21438](https://issues.redhat.com//browse/OSD-21438)
I tested these changes against non-STS clusters, as well as STS clusters using both the old and new flow.

Remove fallbacks to old flow for cloud access

---

README.md
cmd/ocm-backplane/config/troubleshoot_test.go
cmd/ocm-backplane/elevate/elevate.go
pkg/cli/config/config_test.go
pkg/elevate/elevate.go
pkg/elevate/elevate_context.go
pkg/elevate/elevate_test.go
pkg/utils/util.go

_feature/documentation/unit-test_
[OSD-22639](https://issues.redhat.com/browse/OSD-22639)
When running ocm-backplate elevate with an empty string as reason, a prompt will be displayed (if possible) to request the reason.
When a reason is provided (as first argument, on prompt or from previous context), it will be stored in cluster context in order that if a reason is needed for elevation within the following 20 min for the same cluster, no prompt will be displayed and the stored context will be used.
_Resolves [OSD-22639](https://issues.redhat.com//browse/OSD-22639)_
After this change, we will be able to update SOPs using elevate to specify an empty reason, and command will prompt for the reason.

OSD-22639: prompt, store and reuse elevate reason

---

docs/FAQ.md

documentation
https://issues.redhat.com/browse/OSD-19782

Add a FAQ about the ocm-backplane binary

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/ocm/mocks/ocmWrapperMock.go
pkg/ocm/ocmWrapper.go

cleanup
CAD needs to use the GetRestConfig() function, but it doesn't allow passing an ocmConnection programatically. 
To not refactor the whole ocm package/usage, I dupliacted the functions to allow passing and initializing on the fly.

OSD-23312: Refactor GetRestConfig() to allow passing an ocm connection programatically

---

pkg/cli/config/config_test.go

unit-test
Replaces "dummy.com" used in unit tests with "proxy.invalid"  because dummy.com is considered malicious
[OSD-22935](https://issues.redhat.com//browse/OSD-22935)
_Resolves #_

OSD-22935: Remove use of dummy.com from test cases in backplane-cli

---

pkg/cli/config/config.go
pkg/cli/config/config_test.go

bug
The message
```
WARN[0002] No proxy configuration available. This may result in failing commands as backplane-api is only available from select networks.
```
is misleading when a proxies are specified, but they are failing health checks. This PR adds logging when proxies are discarded and falls back to selecting the first specified proxy if all fail health checks.
[OSD-23471](https://issues.redhat.com//browse/OSD-23471)

log when we discard proxies and default to the first proxy if all fail healthchecks

---

pkg/cli/config/config.go

cleanup
In #428 I mistakenly changed the variable name to `proxyHealthCheckURL`, but it was correct before. `config.URL` holds the backplane URL, not the proxy URL.
[OSD-23471](https://issues.redhat.com//browse/OSD-23471)

Fix incorrect variable name and log message

---

cmd/ocm-backplane/console/console.go
pkg/info/info.go

bug
Use the tmp directory instead of the config directory for monitoring plugin config.
The monitoring config doesn't contain sensitive info. The backplane config directory can sometimes be Read-only. So putting the file in tmp directory.
_Resolves #_

Console use tmp dir for monitor plugin conf

---

cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
cmd/ocm-backplane/logout/logout_test.go
pkg/cli/config/config.go
pkg/cli/config/config_test.go

validation mandatory value proxy-url in backplane config validate the PD API KEY in config file if login via PD
_(/feature/)_
There are two parts for this PR:
1. Add validation to the backplane config
The original plan is to make the struct `BackplaneConfiguration` to have the mandatory fields as required, but it turns out the there are multiple ways to setup the proxy-url currently.
- ocm backplane login --proxy-url
- HTTPS_PROXY=xxxx ocm backplane login
- read through the config file
So it is not possible to change the struct. Adding a small function to make sure the proxy url was set by any of above methods, and exit early if it is not set.
2. Validate the pd api key when login via PD
Currently, the PD API Key can be configured in config file only, and the `--pd` will be used in login …

[OSD-21620] Add validation for the backplane config file

---

pkg/credentials/aws.go

feature
When outputting cloud credentials with the `-o env` flag, the current output will contain the region as `AWS_DEFAULT_REGION`. Looking at the [AWS docs](https://docs.aws.amazon.com/sdkref/latest/guide/feature-region.html#feature-region-sdk-compat), this seems to be dropping in favor of AWS_REGION. Furthermore, some AWS SDKs don't even acknowledge the `AWS_DEFAULT_REGION` envar.
Resolves [OSD-23927](https://issues.redhat.com//browse/OSD-23927)

use 'AWS_REGION' instead of 'AWS_DEFAULT_REGION' when formatting credentials output

---

cmd/ocm-backplane/config/troubleshoot.go

bug
Fixes nil pointer deference seg fault during the troubleshoot util
Adds notice in the troubleshoot util for missing config file if not found at the expected path. 
_Resolves #_
This should address the following error when "proxy-url" value is not set in the current configuration file/path, and not provided as an environment var. 
```
[BP]➜ ~/rh_sandbox/backplane-cli/ git:(main) ✗ ./ocm-backplane config troubleshoot
[V] backplane-cli configuration path: /Users/maclark/.config/backplane/config.json
WARN[0001] No proxy configuration available. This may result in failing commands as backplane-api is only available from select networks. 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1036af5ec] …
```

Check for nil ptr proxy-url value in troubleshoot util

---

ci-release.sh

_(bug)_
To ensure remote upstream repo is added based on the job failures logs I got: https://storage.googleapis.com/test-platform-results/logs/branch-ci-openshift-backplane-cli-main-combined-release/1800401130698575872/build-log.txt
https://issues.redhat.com/browse/OSD-20658

[OSD-20658] Updated the ci-release script to ensure remote upstream repo is added

---

go.mod
go.sum

feature: Bump to latest version of https://github.com/openshift/backplane-api
https://issues.redhat.com/browse/OSD-22636
- [-] Included documentation changes with PR

bump: backplane-api client

---

.github/PULL_REQUEST_TEMPLATE.md

unit-test
Add guidelines for the unit test coverage 
_Resolves #_

Add unit test coverage check when creating a PR

---

cmd/ocm-backplane/accessrequest/createAccessRequest.go
cmd/ocm-backplane/accessrequest/expireAccessRequest.go
cmd/ocm-backplane/accessrequest/getAccessRequest.go
cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
go.mod
pkg/ocm/mocks/ocmWrapperMock.go
pkg/ocm/ocmWrapper.go

_(feature)_
OCM offline token disabled, backplane login would fail if OCM not logged in, inform the user to do the ocm login if it is not when executing the backplane commands
_Resolves #OSD-21603_

inform user to login to OCM if the backplane failed due to that

---

pkg/healthcheck/check_proxy.go
pkg/healthcheck/check_proxy_test.go
pkg/healthcheck/check_vpn.go
pkg/healthcheck/check_vpn_test.go
pkg/healthcheck/connectivity_checks.go
pkg/healthcheck/healthcheck_suite_test.go

_(unit-test)_
Updated to use Ginkgo BDD testing framework for my `healthcheck` subcommand to align with the current test style
_Resolves #_
- The main logic of the merged `healthcheck` subcommand is not change but just refactored the test cases using the Ginkgo BDD framework
-  Changed the struct name (e.g below) based on the naming convention
```
// Default implementations
type DefaultNetworkInterfaceImpl struct{}
type DefaultHTTPClientImpl struct {
Client *http.Client
}
```
- `CheckBackplaneAPIConnectivity` function is not covered by the test case since it's just call the existing `CheckAPIConnection()` which defined in the existing `config.GetBackplaneConfiguration`.

Update to use Ginkgo BDD testing framework to align with the exist test style

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/login/login.go

_(bug)_
Enhance readability of healthcheck prompt messages when backplane access failed
context: https://redhat-internal.slack.com/archives/C016S65RNG5/p1723016359859959
The Expected Output with the change
- Error connecting to bp-api
```
ERRO[0006] Connection Error to Backplane API:
ERRO[0006] cannot connect to Backplane API URL: Head "https://api.stage.backplane.openshift.com": proxyconnect tcp: dial tcp: lookup proxy2.squi-001.prod.rdu2.dc.redhat.com: no such host.
[**NOTE:** To troubleshoot the connectivity issues, please run `ocm-backplane health-check`]
```
- Error of login
```
ERRO[0006] Login Attempt Failed:
ERRO[0006] login failed: error from backplane: Status Code: 406.
[**NOTE:** To troubleshoot the connectivity issues, please run `ocm-backplane health-check`]
```

[OSD-25177] Enhance readability of healthcheck prompt messages

---

Makefile
pkg/healthcheck/check_proxy.go
pkg/healthcheck/check_vpn.go
pkg/healthcheck/connectivity_checks.go
pkg/monitoring/monitoring.go

Fix the golang-lint issue

---

pkg/cli/session/session.go

feature
This PR is to expose the error returned by OCM when looking up the cluster.
Printing this error can help user troubleshoot the issue easier.
Before this PR:
```
$ ocm backplane session siwu-test
ERRO[0000] invalid cluster Id siwu-test         
```
After this PR:
```
$ ocm.prod backplane session siwu-test
ERRO[0000] invalid cluster Id siwu-test. error: failed to create OCM connection: please ensure you are logged into OCM by using the command "ocm login --url $ENV"
```
_Resolves #_

feat: print ocm error in backplane session

---

cmd/ocm-backplane/cloud/console.go

Looks like a copy-paste from "ocm-backplane cloud credentials" command made it to "ocm-backplane cloud console"
bug
credentialArgs aren't populated, consoleArgs should be used in the ocm-backplane cloud console command
_Resolves OSD-26222_

Fixing a copy-paste typo of command line args 

---

cmd/ocm-backplane/managedJob/getManagedJob.go
pkg/backplaneapi/clientUtils.go

cleanup
This code removes some unused code, and cleans up some duplicated code paths.
N/A
(was done as part of https://issues.redhat.com/browse/OSD-19766)

Code cleanups from #547

---

Dockerfile
go.mod

feature
Bump go version to 1.22.7
**Note** :  ubi9/ubi image still not supporting golang 1.22 version and it may support in 9.5 version 
_Resolves #_
https://issues.redhat.com/browse/OSD-24733 

Bump go version to 1.22.x

---

cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/login/login.go
pkg/backplaneapi/backplaneapi_suite_test.go
pkg/backplaneapi/clientUtils.go
pkg/backplaneapi/deprecation.go
pkg/backplaneapi/deprecation_test.go

feature
This will allow us to add code in the server to warn the user when their client is old and may be blocked soon.
This is the client side code for https://issues.redhat.com/browse/OSD-19766

Accept deprecation warnings from the server and warn the user

---

README.md
cmd/ocm-backplane/login/login.go
pkg/login/printClusterInfo.go
pkg/login/printClusterInfo_test.go

feature to print cluster info after backplain login into a cluster
Helps to get basic info while troubleshooting 
(https://issues.redhat.com/browse/OSD-25315)
There a couple of things to mention:
1. It covers 49.7 % of code but fails when `PrintAccessProtectionStatus(clusterID)` is called as its required to mock ocmConnection
` Unexpected call to *mocks.MockOCMInterface.SetupOCMConnection([]) at /home/ydiakov/cards/osd-25315/attem_4/backplane-cli/pkg/login/printClusterInfoAfterLogin.go:40 because: there are no expected calls of the method "SetupOCMConnection" for that receiver`

Print cluster info aftger login

---

cmd/ocm-backplane/console/console_test.go
pkg/elevate/elevate.go
pkg/elevate/elevate_test.go

_bug,cleanup_
I wanted to resolve a bug but was unable to even run the tests for this project on main from my macOS system. This does a few things to fix that:
- Update the assertions for what type of containerEngine you get in the `console` command to work across different runtimes
- Resolves an issue where we would leak a kubeconfig file in `pkg/elevate` because we were relying on the default behavior where a kubeconfig is written to the value of `LocationOfOrigin`
There are a lot of other things I noticed while in here that I would like to cleanup to make testing both easier to reason about, and rely less on local state. We should be using a mock filesystem, for example, and not actually modifying any local state (or relying on it).
Additionally, I removed some tests from `console` …

OSD-27228: Modify tests so that they pass on macOS, fix issue with leaking file

---

cmd/ocm-backplane/cloud/common.go

feature
This PR improves the user experience when accessing the cloud console by displaying the returned error message. This enhancement benefits all users, **including those attempting to access lockbox-protected clusters**, by providing clearer error message.
The current error message looks to be sufficiently descriptive, but if adjustments are needed, I recommend updating the error message directly in the [Backplane API](https://gitlab.cee.redhat.com/service/backplane-api/-/blob/master/pkg/auth/authz.go?ref_type=heads#L269-274) for better long-term maintainability.
**Before this PR:**
```
$ ocm-backplane cloud console -b 2f75gfh5sebi2tho8j0pt22lr29ul83v
ERRO[0004] failed to get cloud console for cluster 2f75gfh5sebi2tho8j0pt22lr29ul83v: failed to assume role with isolated backplane …
```

[OSD-25707] feat: print api error message

---

README.md
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/cli/config/config.go
pkg/cli/config/config_test.go

This is an addition to https://github.com/openshift/backplane-cli/pull/561
This PR adds an ability to add a flag in the backplane config and the cluster info will be printed automatically every time without a need to set `--cluster-into` each time
Example
`
{
"proxy-url": ["http://squid.corp.redhat.com:3128/","http://proxy2.squi-001.prod.rdu2.dc.redhat.com:3128/"],
"display-cluster-info": true
}
`
[_Resolves #_
](https://issues.redhat.com/browse/OSD-25315)

Print cluster info by setting a flag in backplane config file.

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
cmd/ocm-backplane/remediation/remediation.go
cmd/ocm-backplane/remediation/remediation_test.go
cmd/ocm-backplane/root.go
go.mod
go.sum
pkg/client/mocks/ClientMock.go
pkg/client/mocks/ClientWithResponsesMock.go
pkg/remediation/remediation.go
pkg/utils/jwt.go
pkg/utils/jwt_test.go

feature
Adds commands to create and delete RBAC for CAD investigations.
This will enable CAD to access kube-api with per remediation scoped down permissions. 
These commands are only allowed for backplane roles which are configured to use remediations ( currently CAD and SREP, see https://gitlab.cee.redhat.com/service/backplane-api/-/merge_requests/378/diffs#c6d8d5258b671d72ca173652ee8826e678b71b62_10_14 )
To learn more about the remediation endpoint in backplane-api, see  https://gitlab.cee.redhat.com/service/backplane-api/-/merge_requests/378
https://issues.redhat.com/browse/OSD-25689

Add commands to create and delete remediations

---

cmd/ocm-backplane/remediation/remediation.go

Adds small info that user is logged in to the cluster as the remediation ( so that one can test RBAC )
_Resolves #_

Add small success info when creating remediation

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/login/login_test.go
pkg/ocm/ocmWrapper.go

_feature_
- The PR improves the output message for service and manager flags for the login command. It provides user to directly export the related variables. For service flag, there was no output related to the namespace or manifestwork which has been added now
- The error message for login has been updated to clarify either management cluster or hive shard accordingly
Output
```
❯ go run ./cmd/ocm-backplane login $ID --service
A list of associated manifestwork for your given cluster can be found using:
oc get manifestworks -n <> -l api.openshift.com/id=$ID
The MC Namespace for the cluster can be exported using:
export MC_NAME=<>
❯ go run ./cmd/ocm-backplane login $ID --manager
Execute the following command to export the list of associated namespaces for your given cluster
export …
```

OSD-27703: fix: Improve output for service and manager flags in login command

---

cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/remediation/remediation.go
cmd/ocm-backplane/remediation/remediation_test.go
pkg/remediation/remediation.go

bug/cleanup, these new commands did not work before.
They were being tested and developed in parallel to backplane-apis remediation feature, which was subject to change.
The backplane feature is now live, so with these commands its possible to create and delete a "remediation" on a cluster.
For more on remediations see https://gitlab.cee.redhat.com/service/backplane-api#remediations
makes the remediation create and delete command work 
https://issues.redhat.com/browse/OSD-27272

Fix remediation commands

---

pkg/cli/config/config.go
pkg/cli/config/config_test.go

feature
This change speeds up the proxy selection code by performing tests on multiple proxies simultaneously.
Resolves https://issues.redhat.com/browse/OSD-22383

Speed up proxy selection code

---

cmd/ocm-backplane/login/login.go

_(bug)_
context: https://redhat-internal.slack.com/archives/C0326L38PEH/p1739149657084669
- For reviewer:
```
./ocm-backplane login 2grfffik8udbvmnbckil30kd7koovam2 --manager
Execute the following command to export the list of associated namespaces for your given cluster
export HCP_NAMESPACE=ocm-int-2grfffik8udbvmnbckil30kd7koovam2-danintdt
export KLUSTERLET_NS=klusterlet-2grfffik8udbvmnbckil30kd7koovam2
export HC_NAMESPACE=ocm-int-2grfffik8udbvmnbckil30kd7koovam2
```
- The corresponding cluster service code snippet [here](https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/blob/master/cmd/clusters-service/service/cluster_deployment_name_calculator.go#L35-39)

Convert integration HCP namesapce

---

pkg/utils/jwt_test.go

cleanup
When I pulled the latest from upstream and pushed to my fork, I got an email from infosec about a potential breach. Once I confirmed that these are all test data and there's no actual secret information in these JWTs, I added the comment to ensure that these are hopefully ignored by the test screeners so that they don't flag as false-positives again.
_Resolves #_

adds notsecret flag to hopefully stop false positives

---

Dockerfile
Makefile
go.mod

Hotfix 
This PR bump Go version 1.23 since backplane CI is already running on 1.23 version 
_Resolves #_

Bump Go 1.23.6 

---

Dockerfile
Makefile
go.mod

_bug_
_Resolves #[OSD-28717](https://issues.redhat.com//browse/OSD-28717)_

OSD-28717: Fix build failures of backplane-cli while bumping to version 1.23

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go
pkg/awsutil/aws_suite_test.go
pkg/awsutil/iam.go
pkg/awsutil/iam_test.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go
pkg/ocm/mocks/ocmWrapperMock.go
pkg/ocm/ocm.go
pkg/ocm/ocm_suite_test.go
pkg/ocm/ocm_test.go

Feature
This PR prevents off-VPN cloud console/credentials access once STS token derived it VPN connection 
https://issues.redhat.com/browse/OSD-19789
* Get cloud console access via connecting to VPN 
* Check the available resources ( like ec2/cloudtrial)
* disconnect from the VPN 
* You shouldn't be able to access the resources 
_Resolves #_

Add off-VPN deny inline policy to prevent unauthorized access

---

cmd/ocm-backplane/login/login.go
pkg/login/additional_login_detector.go
pkg/login/additional_login_detector_test.go

Feature
This adds a check after a successful login to tell the user about other backplane sessions that are currently on the cluster. This should add a bit of a check-and-balance for when MCS is looking at a cluster where SRE might already be paged for it, or conversely if you're responding to a page and see that there are a few other SRE sessions, it might tip you off to look at Service Logs or PD history to see why other SREs may be logged into this cluster already.
Resolves https://issues.redhat.com/browse/OSD-28832
Still a WIP - need to add additional tests and continue to test in different environments.
- If it's a bug fix for an existing sub-command, please cover 70% of the …

Adds check for additional backplane users at login

---

OWNERS

- [] Feature
dding Daniel and Yuri to the owners group
- Closes #

Adding Daniel and Yuri to the owners group

---

.codecov.yml

It will improve the codecoverage of backplane-cli by excluding the mock files which are covered in codecov report
It will exclude files like pkg/ocm/mocks/ocmWrapperMock.go & pkg/backplaneapi/mocks/clientUtilsMock.go
- Closes # [OSD-28995](https://issues.redhat.com/browse/OSD-28995)

[OSD-28995] Update codecov settings 

---

cmd/ocm-backplane/remediation/remediation.go
cmd/ocm-backplane/remediation/remediation_test.go
go.mod
go.sum
pkg/remediation/remediation.go

`ocm-backplane remediation create` is now returning a remediation instance id; this id will be used in place of the remediation name at `ocm-backplane remediation delete` time.
This will allow backplane to have several remediations with the same name in parallel without mixing up the resources created on the target cluster.
- Contributes to [SREP-21](https://issues.redhat.com//browse/SREP-21)
Depends on the following `backplane-api` change which will need to be referenced in `go.mod` & `go.sum` to have the code build successfully:
https://github.com/openshift/backplane-api/pull/19

SREP-21: backplane API is now allocating a remediation instance id for each call to createRemediation

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go

The trusted IPs in OCM are already trust - and should be vetted when introduced.
So for now - as this is breaking production CAD - it seems better to not filter until we can ensure we don't filter out valid users.
The current filtering of the already trusted IPs is breaking CAD as it's not using the proxy, but still is a user of the backplane-CLI.
- Closes #

Remove filtering the IP whitelist.

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go

Allowing all trusted IP lists exceeded the AWS policy character length, and it breaks the bacplane-cli sts assume-role process. This PR limited the number of IPs to keep the policy limit within AWS's valid character length. 
This PR revert back proxy IP filtering and add CAD stg and prod ips 
- Closes #

Add CAD stg and prod IP's to session policy

---

cmd/ocm-backplane/login/login.go
docs/PS1-setup.md
pkg/cli/config/config.go

Adds an optional configuration option `disable-kube-ps1-warning` to be able to conditionally display the warning about setting up the `kube-ps1` function in your terminal.
The motivation for this is I have a custom terminal prompt that includes `~/.kube/config` context information, and desire for less warning output when I login to clusters.
I tested this behavior with default values (nil), and bool/string, which are handled by `viper` for us natively.
- Closes #

Make KUBEPS1 warning optional

---

README.md
cmd/ocm-backplane/cloud/console.go
cmd/ocm-backplane/cloud/credentials.go
cmd/ocm-backplane/config/config.go
cmd/ocm-backplane/config/get.go
cmd/ocm-backplane/config/set.go
cmd/ocm-backplane/login/login.go
cmd/ocm-backplane/managedJob/createManagedJob.go
cmd/ocm-backplane/script/describeScript.go
go.mod
go.sum
pkg/cli/config/config.go
pkg/cli/globalflags/globalflags.go
pkg/login/printClusterInfo.go
pkg/utils/util.go

FedRAMP does not have a proxy and app-gate VPN is required.  This will remove the noise from the output for govcloud users.
A new config item is added to identify govcloud.  When `govcloud: true`
[OSD-29893](https://issues.redhat.com//browse/OSD-29893)
Debugging tests completed
```
{
"version": "0.2.0",
"configurations": [
{
"name": "Login-OSD-West",
"type": "go",
"request": "launch",
"mode": "auto",
"program": "/config/workspace/backplane-cli/cmd/ocm-backplane/",
"env": {},
"args": [
"login",
"--url=https://api-backplane-int.apps.REMOVED.q3zc.i1.devshiftusgov.com",
"REMOVED",
"--verbosity=debug"
]
},
{
"name": "Login-backplane-no-debug",
"type": "go",
"request": "launch",
"mode": "auto",
"program": "/config/workspace/backplane-cli/cmd/ocm-backplane/",
"env": {},
"args": [
"login", …
```

OSD-29893 - Adding Fedramp compatibility

---

cmd/ocm-backplane/console/console.go
cmd/ocm-backplane/console/console_test.go
pkg/container/container.go
pkg/container/container_docker.go
pkg/container/container_podman.go
pkg/container/container_test.go
pkg/container/mocks/containerEngineMock.go

This PR applies the changes in https://github.com/openshift/backplane-cli/pull/718 and add corresponding unit tests.
From OCP 4.17, the monitoring plugin in console no longer require nginx, instead, we should pass a PORT environment variable for it to listen.
This is to fix the issue in https://issues.redhat.com/browse/SREP-608 
https://issues.redhat.com/browse/SREP-993
- Tested locally with MacOS/Podman, works for 4.16 and 4.19 clusters.

[SREP-993] fix: pass env for 4.17+ monitor plugin

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
Makefile
docs/release.md

This PR add a guideline for how we should apply semver practice in backplane-cli.
- Add a PR guideline in CONTRIBUTING.MD. We should specify the type of the PR in the title, so that when the maintainer cut a new release, they can clearly see what kind of changes have been made since the last release.
- Add steps in release.md for maintainer to generate a grouped release note, so that they can decide how to bump the version accordingly.
- Add a target `release-with-note` in Makefile for specifying a custom release note.
https://issues.redhat.com/browse/SREP-943
Example of release note using the new guideline:
```
77b402c Add domain checks for isolated backplane access in isIsolatedBackplaneAccess function
9123aab OSD-29893 - Adding Fedramp compatibility (#693)
4e89950 Capture the SIGINT in …
```

[SREP-943] docs: add guideline for semver release

---

cmd/ocm-backplane/cloud/common.go
cmd/ocm-backplane/cloud/common_test.go
pkg/awsutil/sts.go
pkg/awsutil/sts_test.go

This PR moves inline session policy to the last hop of the assume role sequence
https://issues.redhat.com/browse/SREP-1313
- Closes #

[SREP-1313] feat: Move the inline session policy to the last hop of the assume role sequence
